/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as PromptsRouteImport } from './routes/prompts'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ChecklistRouteImport } from './routes/checklist'
import { Route as CertificateRouteImport } from './routes/certificate'
import { Route as BrandingRouteImport } from './routes/branding'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Stage4RouteImport } from './routes/stage.4'
import { Route as Stage3RouteImport } from './routes/stage.3'
import { Route as Stage2RouteImport } from './routes/stage.2'
import { Route as Stage1RouteImport } from './routes/stage.1'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsRoute = PromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistRoute = ChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificateRoute = CertificateRouteImport.update({
  id: '/certificate',
  path: '/certificate',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandingRoute = BrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Stage4Route = Stage4RouteImport.update({
  id: '/stage/4',
  path: '/stage/4',
  getParentRoute: () => rootRouteImport,
} as any)
const Stage3Route = Stage3RouteImport.update({
  id: '/stage/3',
  path: '/stage/3',
  getParentRoute: () => rootRouteImport,
} as any)
const Stage2Route = Stage2RouteImport.update({
  id: '/stage/2',
  path: '/stage/2',
  getParentRoute: () => rootRouteImport,
} as any)
const Stage1Route = Stage1RouteImport.update({
  id: '/stage/1',
  path: '/stage/1',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/branding': typeof BrandingRoute
  '/certificate': typeof CertificateRoute
  '/checklist': typeof ChecklistRoute
  '/login': typeof LoginRoute
  '/prompts': typeof PromptsRoute
  '/support': typeof SupportRoute
  '/stage/1': typeof Stage1Route
  '/stage/2': typeof Stage2Route
  '/stage/3': typeof Stage3Route
  '/stage/4': typeof Stage4Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/branding': typeof BrandingRoute
  '/certificate': typeof CertificateRoute
  '/checklist': typeof ChecklistRoute
  '/login': typeof LoginRoute
  '/prompts': typeof PromptsRoute
  '/support': typeof SupportRoute
  '/stage/1': typeof Stage1Route
  '/stage/2': typeof Stage2Route
  '/stage/3': typeof Stage3Route
  '/stage/4': typeof Stage4Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/branding': typeof BrandingRoute
  '/certificate': typeof CertificateRoute
  '/checklist': typeof ChecklistRoute
  '/login': typeof LoginRoute
  '/prompts': typeof PromptsRoute
  '/support': typeof SupportRoute
  '/stage/1': typeof Stage1Route
  '/stage/2': typeof Stage2Route
  '/stage/3': typeof Stage3Route
  '/stage/4': typeof Stage4Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/branding'
    | '/certificate'
    | '/checklist'
    | '/login'
    | '/prompts'
    | '/support'
    | '/stage/1'
    | '/stage/2'
    | '/stage/3'
    | '/stage/4'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/branding'
    | '/certificate'
    | '/checklist'
    | '/login'
    | '/prompts'
    | '/support'
    | '/stage/1'
    | '/stage/2'
    | '/stage/3'
    | '/stage/4'
  id:
    | '__root__'
    | '/'
    | '/branding'
    | '/certificate'
    | '/checklist'
    | '/login'
    | '/prompts'
    | '/support'
    | '/stage/1'
    | '/stage/2'
    | '/stage/3'
    | '/stage/4'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrandingRoute: typeof BrandingRoute
  CertificateRoute: typeof CertificateRoute
  ChecklistRoute: typeof ChecklistRoute
  LoginRoute: typeof LoginRoute
  PromptsRoute: typeof PromptsRoute
  SupportRoute: typeof SupportRoute
  Stage1Route: typeof Stage1Route
  Stage2Route: typeof Stage2Route
  Stage3Route: typeof Stage3Route
  Stage4Route: typeof Stage4Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts': {
      id: '/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof PromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklist': {
      id: '/checklist'
      path: '/checklist'
      fullPath: '/checklist'
      preLoaderRoute: typeof ChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificate': {
      id: '/certificate'
      path: '/certificate'
      fullPath: '/certificate'
      preLoaderRoute: typeof CertificateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branding': {
      id: '/branding'
      path: '/branding'
      fullPath: '/branding'
      preLoaderRoute: typeof BrandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stage/4': {
      id: '/stage/4'
      path: '/stage/4'
      fullPath: '/stage/4'
      preLoaderRoute: typeof Stage4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stage/3': {
      id: '/stage/3'
      path: '/stage/3'
      fullPath: '/stage/3'
      preLoaderRoute: typeof Stage3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stage/2': {
      id: '/stage/2'
      path: '/stage/2'
      fullPath: '/stage/2'
      preLoaderRoute: typeof Stage2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stage/1': {
      id: '/stage/1'
      path: '/stage/1'
      fullPath: '/stage/1'
      preLoaderRoute: typeof Stage1RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrandingRoute: BrandingRoute,
  CertificateRoute: CertificateRoute,
  ChecklistRoute: ChecklistRoute,
  LoginRoute: LoginRoute,
  PromptsRoute: PromptsRoute,
  SupportRoute: SupportRoute,
  Stage1Route: Stage1Route,
  Stage2Route: Stage2Route,
  Stage3Route: Stage3Route,
  Stage4Route: Stage4Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
