/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as PromptsRouteImport } from './routes/prompts'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ChecklistRouteImport } from './routes/checklist'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PathRoleIdRouteImport } from './routes/path.$roleId'
import { Route as ModuleModuleIdRouteImport } from './routes/module.$moduleId'
import { Route as ApiSearchChatRouteImport } from './routes/api.search-chat'
import { Route as ApiDocsChatRouteImport } from './routes/api.docs-chat'

const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsRoute = PromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistRoute = ChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PathRoleIdRoute = PathRoleIdRouteImport.update({
  id: '/path/$roleId',
  path: '/path/$roleId',
  getParentRoute: () => rootRouteImport,
} as any)
const ModuleModuleIdRoute = ModuleModuleIdRouteImport.update({
  id: '/module/$moduleId',
  path: '/module/$moduleId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchChatRoute = ApiSearchChatRouteImport.update({
  id: '/api/search-chat',
  path: '/api/search-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsChatRoute = ApiDocsChatRouteImport.update({
  id: '/api/docs-chat',
  path: '/api/docs-chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checklist': typeof ChecklistRoute
  '/docs': typeof DocsRoute
  '/prompts': typeof PromptsRoute
  '/roles': typeof RolesRoute
  '/api/docs-chat': typeof ApiDocsChatRoute
  '/api/search-chat': typeof ApiSearchChatRoute
  '/module/$moduleId': typeof ModuleModuleIdRoute
  '/path/$roleId': typeof PathRoleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checklist': typeof ChecklistRoute
  '/docs': typeof DocsRoute
  '/prompts': typeof PromptsRoute
  '/roles': typeof RolesRoute
  '/api/docs-chat': typeof ApiDocsChatRoute
  '/api/search-chat': typeof ApiSearchChatRoute
  '/module/$moduleId': typeof ModuleModuleIdRoute
  '/path/$roleId': typeof PathRoleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checklist': typeof ChecklistRoute
  '/docs': typeof DocsRoute
  '/prompts': typeof PromptsRoute
  '/roles': typeof RolesRoute
  '/api/docs-chat': typeof ApiDocsChatRoute
  '/api/search-chat': typeof ApiSearchChatRoute
  '/module/$moduleId': typeof ModuleModuleIdRoute
  '/path/$roleId': typeof PathRoleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checklist'
    | '/docs'
    | '/prompts'
    | '/roles'
    | '/api/docs-chat'
    | '/api/search-chat'
    | '/module/$moduleId'
    | '/path/$roleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checklist'
    | '/docs'
    | '/prompts'
    | '/roles'
    | '/api/docs-chat'
    | '/api/search-chat'
    | '/module/$moduleId'
    | '/path/$roleId'
  id:
    | '__root__'
    | '/'
    | '/checklist'
    | '/docs'
    | '/prompts'
    | '/roles'
    | '/api/docs-chat'
    | '/api/search-chat'
    | '/module/$moduleId'
    | '/path/$roleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChecklistRoute: typeof ChecklistRoute
  DocsRoute: typeof DocsRoute
  PromptsRoute: typeof PromptsRoute
  RolesRoute: typeof RolesRoute
  ApiDocsChatRoute: typeof ApiDocsChatRoute
  ApiSearchChatRoute: typeof ApiSearchChatRoute
  ModuleModuleIdRoute: typeof ModuleModuleIdRoute
  PathRoleIdRoute: typeof PathRoleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts': {
      id: '/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof PromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklist': {
      id: '/checklist'
      path: '/checklist'
      fullPath: '/checklist'
      preLoaderRoute: typeof ChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/path/$roleId': {
      id: '/path/$roleId'
      path: '/path/$roleId'
      fullPath: '/path/$roleId'
      preLoaderRoute: typeof PathRoleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/module/$moduleId': {
      id: '/module/$moduleId'
      path: '/module/$moduleId'
      fullPath: '/module/$moduleId'
      preLoaderRoute: typeof ModuleModuleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search-chat': {
      id: '/api/search-chat'
      path: '/api/search-chat'
      fullPath: '/api/search-chat'
      preLoaderRoute: typeof ApiSearchChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/docs-chat': {
      id: '/api/docs-chat'
      path: '/api/docs-chat'
      fullPath: '/api/docs-chat'
      preLoaderRoute: typeof ApiDocsChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChecklistRoute: ChecklistRoute,
  DocsRoute: DocsRoute,
  PromptsRoute: PromptsRoute,
  RolesRoute: RolesRoute,
  ApiDocsChatRoute: ApiDocsChatRoute,
  ApiSearchChatRoute: ApiSearchChatRoute,
  ModuleModuleIdRoute: ModuleModuleIdRoute,
  PathRoleIdRoute: PathRoleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
